### ISSUE TITLE
Warning: LCW invalid configuration error

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/vc-status-list#4]
When running iOS version of LCW, the following warning is triggered:

warn Package @digitalcredentials/vc-status-list has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in [...]/node_modules/@digitalcredentials/vc-status-list/package.json

**Comment by dmitrizagidulin** [comment]
@kayaelle yeah, I think so..
